REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_unzip\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\ResID" -I "D:\MyGitHub\mre_miniz_unzip\src\app\widget" -I "D:\MyGitHub\mre_miniz_unzip\src\app\launcher" -I "D:\MyGitHub\mre_miniz_unzip\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_unzip\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\src\framework" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_unzip\src\component" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_unzip"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_unzip\arm\mre_miniz_unzip.o" -c "d:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\ResID" -I "D:\MyGitHub\mre_miniz_unzip\src\app\widget" -I "D:\MyGitHub\mre_miniz_unzip\src\app\launcher" -I "D:\MyGitHub\mre_miniz_unzip\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_unzip\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\src\framework" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_unzip\src\component" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_unzip"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_miniz_unzip\arm\mre_stdlibio.o" -c "d:\MyGitHub\mre_miniz_unzip\mre_stdlibio.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\ResID" -I "D:\MyGitHub\mre_miniz_unzip\src\app\widget" -I "D:\MyGitHub\mre_miniz_unzip\src\app\launcher" -I "D:\MyGitHub\mre_miniz_unzip\src\app\wallpaper" -I "D:\MyGitHub\mre_miniz_unzip\src\app\screen_lock" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\include\component" -I "D:\MyGitHub\mre_miniz_unzip\include\service" -I "D:\MyGitHub\mre_miniz_unzip\src\framework" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\base" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_miniz_unzip\src\framework\mmi_core" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_miniz_unzip\src\component" -I "D:\MyGitHub\mre_miniz_unzip\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_miniz_unzip"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.axf"  "D:\MyGitHub\mre_miniz_unzip\arm\gccmain.o"  "D:\MyGitHub\mre_miniz_unzip\arm\mre_miniz_unzip.o"  "D:\MyGitHub\mre_miniz_unzip\arm\mre_stdlibio.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.pkd" -e AXF "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.vcproj" "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\mre_miniz_unzip\mre_miniz_unzip.vcproj" "mre_miniz_unzip" "0.1.0" "RDZDX" "3250" "NotSupportBg" "Not Support rotate" "mre_miniz_unzip" "mre_miniz_unzip" "mre_miniz_unzip" "1234567890" "content" " File SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\mre_miniz_unzip\arm D:\MyGitHub\mre_miniz_unzip\build.log

